enabled: true

schedule:
  utc_times:
    - "14:23"
    - "14:27"
    - "14:29"

api:
  base_url: http://localhost:8000
  documents_get: /v1/documents/
  documents_post_batch: /v1/documents/fetch/batch
  ingest_jobs_get: /v1/ingest/jobs/
