"""add next table

Revision ID: 1a92c91b718c
Revises: 20260120_0001
Create Date: 2026-01-20 20:59:19.355581

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '1a92c91b718c'
down_revision = '20260120_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('authors_json', sa.Text(), nullable=True),
    sa.Column('journal', sa.String(length=512), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doi'), 'documents', ['doi'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_doi'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
