# generated by datamodel-codegen:
#   filename:  api.yaml
#   timestamp: 2026-02-08T10:47:40+00:00

from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field


class HealthResponse(BaseModel):
    status: str = Field(..., examples=["ok"])


class ErrorResponse(BaseModel):
    error: str = Field(..., examples=["bad_request"])
    message: str = Field(..., examples=["Invalid request payload"])
    details: dict[str, Any] | None = None


class PubMedQuery(BaseModel):
    id: UUID
    pubmed_query: str
    description: str
    enabled: bool
    last_successful_run_at: AwareDatetime | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime


class PubMedQueryCreate(BaseModel):
    pubmed_query: str
    description: str
    enabled: bool = True


class PubMedQueryUpdate(BaseModel):
    pubmed_query: str
    description: str


class SchedulerStatus(BaseModel):
    enabled: bool
    utc_schedule: list[str]
    next_run_at: AwareDatetime
    last_run_at: AwareDatetime | None = None
    last_run_status: Literal["RUNNING", "SUCCESS", "PARTIAL_SUCCESS", "FAILED"] | None = None


class SchedulerRunCreated(BaseModel):
    run_id: UUID
    status: Literal["RUNNING", "SUCCESS", "PARTIAL_SUCCESS", "FAILED"]
    started_at: AwareDatetime


class QueryExecution(BaseModel):
    query_execution_id: UUID
    query_id: UUID
    status: Literal["RUNNING", "SUCCESS", "PARTIAL_SUCCESS", "FAILED"]
    pubmed_result_count: int | None = None
    doi_resolved_count: int | None = None
    doi_skipped_exists_count: int | None = None
    doi_enqueued_count: int | None = None
    doi_failed_count: int | None = None
    ingest_job_id: UUID | None = None


class RunDoiResult(BaseModel):
    doi: str
    status: Literal["SKIPPED_EXISTS", "ENQUEUED", "INGESTED", "FAILED"]
    error_message: str | None = None


class SchedulerRun(BaseModel):
    run_id: UUID
    status: Literal["RUNNING", "SUCCESS", "PARTIAL_SUCCESS", "FAILED"]
    started_at: AwareDatetime
    finished_at: AwareDatetime | None = None
    queries: list[QueryExecution]
